default:
  dora_dir: /cs/labs/adiyoss/aarontaub/thesis/audiocraft/code
  partitions:
    global: debug
    team: debug
  reference_dir: /tmp
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /cs/labs/adiyoss/aarontaub/thesis/audiocraft/code
  partitions:
    global: debug
    team: debug
  reference_dir: /tmp
